---
- name: Install Network Manager
  package:
    name: NetworkManager
  when: disable_networkmanager is undefined or not disable_networkmanager
- name: Collect package facts
  package_facts:
    manager: "auto"
- name: Disable Network Manager
  service:
    name: NetworkManager
    state: stopped
    enabled: no
  when:
    - disable_networkmanager is defined
    - disable_networkmanager
    - "'NetworkManager' in ansible_facts.packages"
- name: Enable Network Manager
  service:
    name: NetworkManager
    state: started
    enabled: yes
  when: disable_networkmanager is undefined or not disable_networkmanager
- name: Install nmcli remote tools
  package:
    name: NetworkManager-glib
  when: nmcli_remove_conns is defined
- name: Remove interface
  nmcli:
    conn_name: "{{ item }}"
    state: absent
  with_items: "{{ nmcli_remove_conns }}"
  when: nmcli_remove_conns is defined
- fail:
    msg: "'auto' net_conf no longer supported"
  when: net_conf is defined and net_conf == 'auto'
- block:
    - name: Disable cloud-init pre
      file:
        state: directory
        path: /etc/cloud
    - name: Disable cloud-init
      file:
        state: touch
        path: /etc/cloud/cloud-init.disabled
    - name: fix /etc/hosts
      template:
        src: etc_hosts
        dest: /etc/hosts
    - include_role:
        name: firewalld
      when: "firewalld_enable is undefined or firewalld_enable"
    - include_role:
        name: disable-firewalld
      when: "firewalld_enable is defined and not firewalld_enable"
    - include_tasks: configure-interface.yml
      with_items: "{{ netconfigs }}"
    - include_tasks: configure-dns.yml
      with_items: "{{ dnsconfigs }}"
    - name: Configure network manager settings
      template:
        src: NetworkManager.conf
        dest: /etc/NetworkManager/NetworkManager.conf
      notify:
        - reload nmcli
      when: disable_networkmanager is undefined or not disable_networkmanager
    - meta: flush_handlers
  when: net_conf is defined and net_conf == 'explicit'
- include_tasks: openvpn.yml
  when: disable_networkmanager is undefined or not disable_networkmanager
